application: bavulanekoysam
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: staticfiles
- url: /favicon\.ico
  static_files: staticfiles/img/favicon.ico
  upload: staticfiles/img/favicon\.ico
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
